Fix theme dispatch across sessions

diff --git a/libs/clipboard b/libs/clipboard
--- a/libs/clipboard
+++ b/libs/clipboard
@@ -21,37 +21,28 @@
 # Pass a command to STDIN to dispatch to all hx instances in the window
 # ":theme "
 
- # kill pane with flag --exit
+ # mAKE SURE THE MARK IS AN EDITOR
+#!/bin/bash
 
-STDIN=$(cat -)
+# First, check if the 'xclip' command exists
+if ! command -v xclip >/dev/null; then
+    echo "Error: xclip is not installed. Please install it to use this script." >&2
+    exit 1
+fi
 
-# List of pane titles
-# running=($(tmux list-panes -aF "#S:#I.#P #{pane_title}"))
+# Check if standard input is connected to a terminal
+if [ -t 0 ]; then
+    # If it is a terminal, it means no data is being piped in.
+    # Print a usage message to standard error and exit.
+    echo "Usage: <command> | $(basename "$0")" >&2
+    echo "Example: ls -l | $(basename "$0")" >&2
+    exit 0
+fi
 
-# All normal mode
-tmux list-panes -aF "#S:#I.#P #{pane_title}" | \
-grep ' hx' | \
-awk '{print $1}' | \
-xargs -I TARGET tmux send-keys -t TARGET Escape
+# If we're here, data is being piped.
+# Pipe STDIN directly to xclip.
+# This is more efficient than storing it in a variable.
+xclip -selection clipboard
 
-#Nb: Using two loops is safer here to avoid writing in the buffer
-sleep 0.2
-
-# Keys
-tmux list-panes -aF "#S:#I.#P #{pane_title}" | \
-grep ' hx' | \
-awk '{print $1}' | \
-xargs -I TARGET tmux send-keys -t TARGET "$STDIN" C-m
-
-
-# # Loop through all pane titles
-# for index in "${!running[@]}"; do
-#   # Checkge
-#  if the title contains the string "hx"
-#   if [[ "${running[$index]}" == *"hx"* ]]; then
-#     tmux send-keys -t "$index" Escape
-#     # On the lower limit, text might get introduced in the buffer ...
-#     sleep 0.08 # 80ms Depends the machine env, can be reduced or even deleted
-#     tmux send-keys -t "$index" "$STDIN" ENTER
-#   fi
-# done
+# Optional: Add a notification to confirm success
+# echo "Copied to clipboard." >&2
